export const GET_WISATA_DAERAH = 'GET_WISATA_DAERAH';
export const GET_EKSPLORASI = 'GET_EKSPLORASI';
export const GET_MAPGEOJSON = 'GET_MAPGEOJSON';
export const GET_TYPE_PLACE = 'GET_TYPE_PLACE'; // kategori
export const GET_PLACE_BYTYPE = 'GET_PLACE_BYTYPE';
export const GET_PLACE = 'GET_PLACE';
export const GET_PLACE_DETAIL = 'GET_PLACE_DETAIL';

export const WISATA_DAERAH_ERROR = 'WISATA_DAERAH_ERROR';
export const EKSPLORASI_ERROR = 'EKSPLORASI_ERROR';
export const PLACE_ERROR = 'PLACE_ERROR';
export const TYPE_PLACE_ERROR = 'TYPE_PLACE_ERROR';
export const PLACE_BYTPE_ERROR = 'PLACE_BYTPE_ERROR';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_KONTAK = 'ADD_KONTAK';
