export const GET_WISATA_DAERAH = 'GET_WISATA_DAERAH';
export const GET_EKSPLORASI = 'GET_EKSPLORASI';
export const GET_MAPGEOJSON = 'GET_MAPGEOJSON';
export const GET_TYPE_PLACE = 'GET_TYPE_PLACE'; // kategori
export const GET_PLACE_BYTYPE = 'GET_PLACE_BYTYPE';
export const GET_PLACE = 'GET_PLACE';
export const GET_PLACES = 'GET_PLACES';
export const GET_PLACE_COMMENT = 'GET_PLACE_COMMENT';
export const GET_PLACE_DETAIL = 'GET_PLACE_DETAIL';

export const PLACES_REQUEST = 'PLACES_REQUEST';

export const WISATA_DAERAH_ERROR = 'WISATA_DAERAH_ERROR';
export const EKSPLORASI_ERROR = 'EKSPLORASI_ERROR';
export const PLACE_ERROR = 'PLACE_ERROR';
export const PLACE_DETAIL_ERROR = 'PLACE_DETAIL_ERROR';
export const TYPE_PLACE_ERROR = 'TYPE_PLACE_ERROR';
export const PLACE_BYTPE_ERROR = 'PLACE_BYTPE_ERROR';
export const PLACE_COMMENT_ERROR = 'PLACE_COMMENT_ERROR';
export const PLACES_ERROR = 'PLACES_ERROR';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_KONTAK = 'ADD_KONTAK';

export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';
export const ADD_KONTAK_ERROR = 'ADD_KONTAK_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SEARCH = 'SEARCH';
export const SEARCH_ERROR = 'SEARCH_ERROR';
